services:
  frontend:
    image: assetto:latest
    container_name: assetto
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3004:3004"
    environment:
      - PORT=3004